const numero1 = 20;
const numero3 = 30;


console.log(numero1);

/* Try catch es a prueba de errores para situaciones 
especificas */
try { //significa intenta hacer lo siguiente
    console.log(numero2);
} catch (error) { //cacha el error si lo hay y muestralo
    console.log(error);
}

console.log(numero3);